### ISSUE TITLE
git dolfinx problem

### ISSUE THREAD

**Issue by ezhilmathik** [jhale/fenicsx-iris-cluster#7]
Hi, 

I had some issues with my previous installation, then I tried to install it today. 
But then I am having some issue with dolfinx branch, could you please tell me how to fix it this issue ?

```
Cloning into 'dolfinx'...
Applying: Use parmetis by default.
error: patch failed: cpp/dolfinx/graph/partition.cpp:23
error: cpp/dolfinx/graph/partition.cpp: patch does not apply
Patch failed at 0001 Use parmetis by default.
The copy of the patch that failed is found in:
   /mnt/irisgpfs/users/user-name/fenicsx-iris-master-r24/dolfinx/.git/rebase-apply/patch
When you have resolved this problem, run "git am --resolved".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

**Comment by ezhilmathik** [comment]
the previous installation is working now, there was some issue with the file system, I suppose. the computation was stalled when it tried to load the import libraries.

**Comment by jhale** [comment]
The patch to force the use of parmetis is no longer necessary, I've removed it.
